### ISSUE TITLE
Invalid messages in bad message vector

### ISSUE THREAD

**Issue by mycognosist** [ssb-ngi-pointer/go-metafeed#18]
I think I may have found some invalid messages in https://github.com/ssb-ngi-pointer/go-metafeed/blob/master/testvector-metafeed-bad-messages.json

All of them occur in a pair of encoded messages where the first message should be valid and the second message should be invalid. When I attempt to validate the first message in the pair, I encounter an error with the `contentSection` :

```js
const msgBuf = Buffer.from(badVec.Cases[10].Entries[0].EncodedData, 'hex')
// sequence is 1 for Entries[0], therefore `previous` and `hmacKey` parameters are both null
const msgVal = bb.decodeAndValidateSingle(msgBuf, null, null)
// returns a decoded `msgVal` object or `Error`
console.log(msgVal)
```

```shell
Error: invalid message: contentSection object with length undefined is incorrect, expected a list of content and contentSignature
```

If I manually decode `Cases[10].Entries[0]` :

```js
console.log(bfe.decode(bencode.decode(Buffer.from(badVec.Cases[10].Entries[0].EncodedData, 'hex'))))
```

```
[
  [
    '@rqNgSOWOMNc8rhnNu4bd79NcrMQDpUY5Rq+GkBXqpmU=.bbfeed-v1',
    1,
    null,
    0,
    { i: 1, type: <Buffer 74 65 73 74> }   <--- this should be an array of length 2
  ],
  'hga+dReXhFPwz7pFmOHhY2pbEz7sWN7StdXXKK0jv+/EseoLx+Rcss+otLo0SJ/skxC5Fjx05Agx/9asrI6DCQ==.sig.ed25519'
]
```

-----

I believe the following entries are incorrectly invalid:

2.1: previous with bad TFK type
`badVec.Cases[3].Entries[0]`

2.2: previous with bad TFK format
`badVec.Cases[4].Entries[0]`

2.3: previous with bad TFK length
`badVec.Cases[5].Entries[0]`

3.2: 2nd message has wrong previous
`badVec.Cases[7].Entries[0]`

5.1: two messages with bad sequences (1 and 3)
`badVec.Cases[10].Entries[0]`

**Comment by cryptix** [comment]
ah, interesting. I see... I suspected this might be a problem but glanced over it.

In my implementation content and message validation are two parts, so you can have messages where the content isn't in this form:
 
```
[
  {actualContent...},
  "subfeed-signature"
]
```

**Comment by mycognosist** [comment]
Hmm that makes sense. On the JS side I return a decoded `msgVal` object after validation, with fields for `content` and `contentSignature` (if `contentSection` isn't encrypted). I wonder if I should rather simply return `content` and have the caller deal with it further... @arj03, keen to hear your thoughts here.

```js
// validation stuff above...
const msgVal = {
  author,
  sequence,
  previous,
  timestamp,
  signature,
}

if (isBoxedString(contentSection)) {
  msgVal.content = contentSection
} else {
  if (!(Array.isArray(contentSection) && contentSection.length === 2))
    return new Error(
      `invalid message: contentSection ${typeof contentSection} with length ${
        contentSection.length
      } is incorrect, expected a list of content and contentSignature`
    )
  
  const [content, contentSignature] = contentSection
  msgVal.content = content
  msgVal.contentSignature = contentSignature
}

return msgVal
```

**Comment by mycognosist** [comment]
Also just happy to know that I wasn't losing the plot thinking the messages were invalid 😅

**Comment by cryptix** [comment]
The main idea was that these kinds of _invalids_ wouldn't depend on the content at all but I can see your point, too. At some point arj and I discussed doing the content validation in the views that consume and alter the local state of a metafeed.

For future reference the creation code is here:

https://github.com/ssb-ngi-pointer/go-metafeed/blob/412e98c9e92cb94a67a9c22fe14d976a17e23645/internal/vectors/gen_bad_vector1_messages_test.go#L215

It's not super complicated to a add a subfeed signature, i just wanted to spare the dance of actually creating and adding a subfeed and would suggest to just add it to the metadata, i think.

**Comment by arj03** [comment]
Right its a bit of a slippery slope once you start adding rules here, it is very tempting to say that it should follow the same rules as higher level validation if content is not encrypted. That said I would argue that adding a requirement that content must either be encrypted or be an array of size 2 sounds ok. We already have the following other rule:

```
The contentSignature field inside a decrypted contentSection MUST use the subfeed's cryptographic keypair.
```

That way you at least can be sure about the shape of things, but the semantics are tested later on.

**Comment by mycognosist** [comment]
I should have explicitly stated in my first message that the validation I'm currently testing with these vectors is in [ssb-bendy-butt](https://github.com/ssb-ngi-pointer/ssb-bendy-butt).

> That said I would argue that adding a requirement that content must either be encrypted or be an array of size 2 sounds ok.

I would agree with this. That's how the shape is defined in the [bendy-butt-spec](https://github.com/ssb-ngi-pointer/bendy-butt-spec#specification) criteria. I don't believe `contentSignature` verification lies in the domain of bendy-butt, since the spec doesn't specify the signing keypair:

> "MAY be different from the author keypair (for example, under the meta feeds spec, this will be the subfeed keypair)"

**Comment by cryptix** [comment]
So just to recap: just making it an array with two elements is fine. Doesn't even have to be a valid signature. Right?

**Comment by mycognosist** [comment]
Yup, that's sufficient for the purpose of validating messages according to the spec. `contentSignature` verification is out of scope for bendy-butt.
